name: BlockLog
version: 1.0
api-version: 1.13
main: net.codingarea.blocklog.BlockLogPlugin
author: KxmischesDomi

commands:
  logstick:
    permission: blocklog.logstick
    description: Gives a Stick with which you can check a Block Log
  interactstick:
    permission: blocklog.interactstick
    description: Gives a Stick with which you can check a Interaction Log